namespace: monitoring

images:
  genaiService:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-genai-service
    tag: latest
  adminServer:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-admin-server
    tag: latest
  customersService:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-customers-service
    tag: monitoring
  vetsService:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-vets-service
    tag: monitoring
  visitsService:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-visits-service
    tag: monitoring
  apiGateway: 
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-api-gateway
    tag: latest
  discoveryServer:
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-discovery-server
    tag: latest
  configServer: 
    repository: registry.caotienminh.software/springcommunity/spring-petclinic-config-server
    tag: latest
  tracingServer:
    repository: registry.caotienminh.software/springcommunity/zipkin-server
    tag: latest
  prometheusServer:
    repository: docker.io/prom/prometheus
    tag: latest
  grafanaServer:
    repository: grafana/grafana
    tag: latest
  lokiServer:
    repository: docker.io/grafana/loki
    tag: 2.9.6
  alloyServer:
    repository: grafana/alloy
    tag: latest
  alertManager:
    repository: registry.caotienminh.software/springcommunity/alertanager
    tag: latest

imagePullSecrets:
  name: regcred

config:
  discoveryServer:
    url: http://discovery-server:8761
  configServer: 
    url: http://config-server:8888

hostname:
  genaiService:
    name: genai-service
  adminServer:
    name: admin-server
  customersService:
    name: customers-service
  vetsService:
    name: vets-service
  visitsService:
    name: visits-service
  apiGateway: 
    name: api-gateway
  discoveryServer:
    name: discovery-server
  configServer: 
    name: config-server
  tracingServer: 
    name: tracing-server
  prometheusServer:
    name: prometheus-server
  grafanaServer:
    name: grafana-server
  lokiServer:
    name: loki-server
  alloyServer:
    name: alloy-server
  alertManager:
    name: alert-manager
